version: "3.3"

services:

  web:
    build: ./
    volumes:
      - ./:/var/www/html
    env_file: .env
    ports:
      - "8081:80"

  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dopazo
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
